version: 0.0
os: linux
files:
  - source: /script.sh
    destination: /home/ec2-user/
hooks:
  AfterInstall:
    - timeout: 300
      runas: ec2-user
      location: script.sh nagarajcap/RestTests Rest.yml
    - timeout: 300
      runas: ec2-user
      location: script.sh nagarajcap/WSTests wstests.yml
    - timeout: 300
      runas: ec2-user
      location: script.sh nagarajcap/Rest-Python python.yml


